name: CI
on: 
  push:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout respository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: check Docker version
        run: docker --version

      - name: Build all Docker images
        run: |
          docker build -t api-gateway ./api-gateway
          docker build -t user-service ./user-service
          docker build -t template-service ./template-service
          docker build -t email-service ./email-service
          docker build -t push-service ./push-service

      - name: Run tests placeholder
        run: echo "Add your tests here"
